[package]
name = "wdict"
authors = ["pyqlsa"]
description = "Create dictionaries by scraping webpages."
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/pyqlsa/wdict"
repository = "https://github.com/pyqlsa/wdict"
include = [
  "**/*.rs",
  "Cargo.toml",
  "Cargo.lock",
]

[dependencies]
async-recursion = { version = "1.0.4" }
clap = { version = "4.3.8", features = ["derive"] }
deunicode = { version = "1.3.3" }
reqwest = { version = "0.11.18" }
scraper = { version = "0.17.1" }
tokio = { version = "1.28.2", features = ["full"] }
